# Generated by Django 4.0 on 2022-07-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=50, verbose_name='Telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Confiserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=50, verbose_name='Telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse')),
                ('nombre_magasin', models.CharField(max_length=120, verbose_name='Nombre_magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Matière_première',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('quantite', models.IntegerField(verbose_name='Quantite')),
            ],
        ),
        migrations.CreateModel(
            name='Point_de_vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse')),
                ('nombre_point_de_vente', models.CharField(max_length=120, verbose_name='Nombre_point_de_vente')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('conditionnement', models.CharField(max_length=100, verbose_name='Conditionnement')),
                ('quantite', models.IntegerField(verbose_name='Quantite')),
            ],
        ),
        migrations.CreateModel(
            name='Fabriquant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=50, verbose_name='Telephone')),
                ('confiserie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrie_app.confiserie')),
            ],
        ),
    ]
