# Generated by Django 4.0 on 2022-07-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrie_app', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterField(
            model_name='matière_première',
            name='quantite',
            field=models.CharField(max_length=100, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.CharField(max_length=100, verbose_name='Quantite'),
        ),
    ]
