# Generated by Django 4.0 on 2022-08-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrie_app', '0004_delete_userprofile_alter_matière_première_quantite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fabriquant',
            new_name='Fabricant',
        ),
    ]
